<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Code</title>
    <style>
        #code_snippet
        {
            width: 600;
            font: 1em sans-serif;
            background-color: lightgrey;
            border: gray;
            border-style: initial;
        }
        #load_date
        {
            color:green;
            font: 1em sans-serif;
        }
    </style>
</head>
<body>
<span id=\"load_date\">${date}</span>
<pre id=\"code_snippet\">${code}</pre>
</body>
</html>